version: '2'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    container_name: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    container_name: adminer

networks:
  web:
    external: true
