version: '2'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    container_name: postgres
    networks:
      - local

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    container_name: adminer
    networks:
      - local

networks:
  local:
    external: true
